In [3]:
import mysql.connector

queries = [
    '''
        SELECT ProjectID, assignment.EmployeeNumber, LastName, 
            FirstName, OfficePhone
        FROM assignment
        INNER JOIN employee 
        ON assignment.EmployeeNumber = employee.EmployeeNumber;
    ''',
    '''
        SELECT p.ProjectID, ProjectName, p.Department,
            e.EmployeeNumber, LastName, FirstName, OfficePhone
        FROM assignment AS a
        JOIN employee AS e
        ON e.EmployeeNumber = a.EmployeeNumber
        JOIN project AS p
        ON p.ProjectID = a.ProjectID;
    ''',
    '''
        SELECT p.ProjectID, ProjectName, p.Department, d.DepartmentPhone,
            e.EmployeeNumber, LastName, FirstName, OfficePhone
        FROM assignment AS a
        JOIN employee AS e
        ON e.EmployeeNumber = a.EmployeeNumber
        JOIN project AS p
        ON p.ProjectID = a.ProjectID
        JOIN department AS d
        ON d.DepartmentName = p.Department;
    ''',

    '''
        SELECT p.ProjectID, ProjectName, p.Department, d.DepartmentPhone,
            e.EmployeeNumber, LastName, FirstName, OfficePhone
        FROM assignment AS a
        JOIN employee AS e
        ON e.EmployeeNumber = a.EmployeeNumber
        JOIN project AS p
        ON p.ProjectID = a.ProjectID
        JOIN department AS d
        ON d.DepartmentName = p.Department
        WHERE p.Department = "Sales and Marketing";
    ''',
    '''
        SELECT COUNT(*) AS NumberOfMarketingDeptProjects
        FROM project
        WHERE Department = "Sales and Marketing";
    ''',
    '''
        SELECT SUM(MaxHours) As TotalMaxHrsForMKTGDeptProjects
        FROM project
        WHERE Department =  "Sales and Marketing";
    ''',

    '''
        SELECT AVG(MaxHours) AS NumberOfMarketingDeptProjects
        FROM project
        WHERE Department = "Sales and Marketing";
    ''',
    '''
        SELECT Department, COUNT(*)AS NumberOfDeptProjects
        FROM project
        GROUP BY Department;
    '''
]

cnx = mysql.connector.connect(user="root", password="*.Dani_~", host="127.0.0.1", database="hw2")

cursor  = cnx.cursor(buffered=True)

#This is just to print the letters of the exercises
# from their int values in the loop
ch = ord("A")

# Go through the query strings and print out the results.
for query in queries:
    print("******************** " + chr(ch) + " ********************\n")
    ch += 1
    cursor.execute(query)
    for item in cursor:
        print(item)
    print("\n")

cnx.close()

******************** A ********************

(1000, 1, 'Jacobs', 'Mary', '360-285-8110')
(1100, 1, 'Jacobs', 'Mary', '360-285-8110')
(1400, 1, 'Jacobs', 'Mary', '360-285-8110')
(1500, 1, 'Jacobs', 'Mary', '360-285-8110')
(1200, 3, 'Bandalone', 'Richard', '360-285-8210')
(1300, 3, 'Bandalone', 'Richard', '360-285-8210')
(1600, 3, 'Bandalone', 'Richard', '360-285-8210')
(1000, 6, 'Evans', 'Ken', '360-285-8410')
(1100, 6, 'Evans', 'Ken', '360-285-8410')
(1200, 6, 'Evans', 'Ken', '360-285-8410')
(1300, 6, 'Evans', 'Ken', '360-285-8410')
(1400, 6, 'Evans', 'Ken', '360-285-8410')
(1500, 6, 'Evans', 'Ken', '360-285-8410')
(1600, 6, 'Evans', 'Ken', '360-285-8410')
(1200, 7, 'Abernathy', 'Mary', '360-285-8420')
(1600, 7, 'Abernathy', 'Mary', '360-285-8420')
(1200, 8, 'Caruthers', 'Tom', '360-285-8430')
(1300, 8, 'Caruthers', 'Tom', '360-285-8430')
(1600, 8, 'Caruthers', 'Tom', '360-285-8430')
(1300, 9, 'Jones', 'Heather', '360-285-8440')
(1000, 10, 'Numoto', 'Ken', '360-287-8510')
(1100, 10, 'Numoto', 'Ken', '360-287-8510')
(1400, 10, 'Numoto', 'Ken', '360-287-8510')
(1500, 10, 'Numoto', 'Ken', '360-287-8510')
(1100, 11, 'Granger', 'Linda', '360-287-8520')
(1500, 11, 'Granger', 'Linda', '360-287-8520')
(1000, 16, 'Smith', 'Mary', '360-287-8810')
(1400, 16, 'Smith', 'Mary', '360-287-8810')
(1000, 17, 'Jackson', 'Tom', '360-287-8820')
(1400, 17, 'Jackson', 'Tom', '360-287-8820')


******************** B ********************

(1000, '2017 Q3 Production Plan', 'Production', 1, 'Jacobs', 'Mary', '360-285-8110')
(1000, '2017 Q3 Production Plan', 'Production', 6, 'Evans', 'Ken', '360-285-8410')
(1000, '2017 Q3 Production Plan', 'Production', 10, 'Numoto', 'Ken', '360-287-8510')
(1000, '2017 Q3 Production Plan', 'Production', 16, 'Smith', 'Mary', '360-287-8810')
(1000, '2017 Q3 Production Plan', 'Production', 17, 'Jackson', 'Tom', '360-287-8820')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', 1, 'Jacobs', 'Mary', '360-285-8110')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', 6, 'Evans', 'Ken', '360-285-8410')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', 10, 'Numoto', 'Ken', '360-287-8510')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', 11, 'Granger', 'Linda', '360-287-8520')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', 3, 'Bandalone', 'Richard', '360-285-8210')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', 6, 'Evans', 'Ken', '360-285-8410')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', 7, 'Abernathy', 'Mary', '360-285-8420')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', 8, 'Caruthers', 'Tom', '360-285-8430')
(1300, '2017 Q3 Tax Preparation', 'Accounting', 3, 'Bandalone', 'Richard', '360-285-8210')
(1300, '2017 Q3 Tax Preparation', 'Accounting', 6, 'Evans', 'Ken', '360-285-8410')
(1300, '2017 Q3 Tax Preparation', 'Accounting', 8, 'Caruthers', 'Tom', '360-285-8430')
(1300, '2017 Q3 Tax Preparation', 'Accounting', 9, 'Jones', 'Heather', '360-285-8440')
(1400, '2017 Q4 Production Plan', 'Production', 1, 'Jacobs', 'Mary', '360-285-8110')
(1400, '2017 Q4 Production Plan', 'Production', 6, 'Evans', 'Ken', '360-285-8410')
(1400, '2017 Q4 Production Plan', 'Production', 10, 'Numoto', 'Ken', '360-287-8510')
(1400, '2017 Q4 Production Plan', 'Production', 16, 'Smith', 'Mary', '360-287-8810')
(1400, '2017 Q4 Production Plan', 'Production', 17, 'Jackson', 'Tom', '360-287-8820')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', 1, 'Jacobs', 'Mary', '360-285-8110')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', 6, 'Evans', 'Ken', '360-285-8410')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', 10, 'Numoto', 'Ken', '360-287-8510')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', 11, 'Granger', 'Linda', '360-287-8520')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', 3, 'Bandalone', 'Richard', '360-285-8210')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', 6, 'Evans', 'Ken', '360-285-8410')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', 7, 'Abernathy', 'Mary', '360-285-8420')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', 8, 'Caruthers', 'Tom', '360-285-8430')


******************** C ********************

(1000, '2017 Q3 Production Plan', 'Production', '360-287-8800', 1, 'Jacobs', 'Mary', '360-285-8110')
(1000, '2017 Q3 Production Plan', 'Production', '360-287-8800', 6, 'Evans', 'Ken', '360-285-8410')
(1000, '2017 Q3 Production Plan', 'Production', '360-287-8800', 10, 'Numoto', 'Ken', '360-287-8510')
(1000, '2017 Q3 Production Plan', 'Production', '360-287-8800', 16, 'Smith', 'Mary', '360-287-8810')
(1000, '2017 Q3 Production Plan', 'Production', '360-287-8800', 17, 'Jackson', 'Tom', '360-287-8820')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 1, 'Jacobs', 'Mary', '360-285-8110')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 6, 'Evans', 'Ken', '360-285-8410')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 10, 'Numoto', 'Ken', '360-287-8510')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 11, 'Granger', 'Linda', '360-287-8520')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', '360-285-8400', 3, 'Bandalone', 'Richard', '360-285-8210')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', '360-285-8400', 6, 'Evans', 'Ken', '360-285-8410')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', '360-285-8400', 7, 'Abernathy', 'Mary', '360-285-8420')
(1200, '2017 Q3 Portfolio Analysis', 'Finance', '360-285-8400', 8, 'Caruthers', 'Tom', '360-285-8430')
(1300, '2017 Q3 Tax Preparation', 'Accounting', '360-285-8405', 3, 'Bandalone', 'Richard', '360-285-8210')
(1300, '2017 Q3 Tax Preparation', 'Accounting', '360-285-8405', 6, 'Evans', 'Ken', '360-285-8410')
(1300, '2017 Q3 Tax Preparation', 'Accounting', '360-285-8405', 8, 'Caruthers', 'Tom', '360-285-8430')
(1300, '2017 Q3 Tax Preparation', 'Accounting', '360-285-8405', 9, 'Jones', 'Heather', '360-285-8440')
(1400, '2017 Q4 Production Plan', 'Production', '360-287-8800', 1, 'Jacobs', 'Mary', '360-285-8110')
(1400, '2017 Q4 Production Plan', 'Production', '360-287-8800', 6, 'Evans', 'Ken', '360-285-8410')
(1400, '2017 Q4 Production Plan', 'Production', '360-287-8800', 10, 'Numoto', 'Ken', '360-287-8510')
(1400, '2017 Q4 Production Plan', 'Production', '360-287-8800', 16, 'Smith', 'Mary', '360-287-8810')
(1400, '2017 Q4 Production Plan', 'Production', '360-287-8800', 17, 'Jackson', 'Tom', '360-287-8820')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 1, 'Jacobs', 'Mary', '360-285-8110')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 6, 'Evans', 'Ken', '360-285-8410')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 10, 'Numoto', 'Ken', '360-287-8510')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 11, 'Granger', 'Linda', '360-287-8520')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', '360-285-8400', 3, 'Bandalone', 'Richard', '360-285-8210')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', '360-285-8400', 6, 'Evans', 'Ken', '360-285-8410')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', '360-285-8400', 7, 'Abernathy', 'Mary', '360-285-8420')
(1600, '2017 Q4 Portfolio Analysis', 'Finance', '360-285-8400', 8, 'Caruthers', 'Tom', '360-285-8430')


******************** D ********************

(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 1, 'Jacobs', 'Mary', '360-285-8110')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 6, 'Evans', 'Ken', '360-285-8410')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 10, 'Numoto', 'Ken', '360-287-8510')
(1100, '2017 Q3 Marketing Plan', 'Sales and Marketing', '360-287-8500', 11, 'Granger', 'Linda', '360-287-8520')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 1, 'Jacobs', 'Mary', '360-285-8110')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 6, 'Evans', 'Ken', '360-285-8410')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 10, 'Numoto', 'Ken', '360-287-8510')
(1500, '2017 Q4 Marketing Plan', 'Sales and Marketing', '360-287-8500', 11, 'Granger', 'Linda', '360-287-8520')


******************** E ********************

(2,)


******************** F ********************

(Decimal('270.00'),)


******************** G ********************

(Decimal('135.000000'),)


******************** H ********************

('Accounting', 1)
('Finance', 2)
('Production', 2)
('Sales and Marketing', 2)